version: '3.8'

services:
  recipe-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    # Optional: Mount recipes for development (commented out for production)
    # volumes:
    #   - ./data/recipes.json:/app/data/recipes.json:ro